/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author lalo2
 */
public class Gastos extends javax.swing.JFrame {

    /**
     * Creates new form Gastos
     */
    public Gastos() {
        initComponents();
        mostrardatos("");
    }
           Conectar cc = new Conectar();
           Connection cn = cc.conexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        B_volver = new javax.swing.JLabel();
        B_altas = new javax.swing.JButton();
        B_borrar = new javax.swing.JButton();
        B_consultas = new javax.swing.JButton();
        B_modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGastos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        P_buscar1 = new javax.swing.JPanel();
        txtCodigoConsulta = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GASTOS");

        B_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_volver)
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(751, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B_volver))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 80);

        B_altas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_altas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_24px.png"))); // NOI18N
        B_altas.setText("Altas");
        B_altas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_altas.setContentAreaFilled(false);
        B_altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_altasActionPerformed(evt);
            }
        });
        getContentPane().add(B_altas);
        B_altas.setBounds(10, 90, 120, 40);

        B_borrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delete_48px.png"))); // NOI18N
        B_borrar.setText("Borrar");
        B_borrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_borrar.setContentAreaFilled(false);
        B_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(B_borrar);
        B_borrar.setBounds(140, 90, 130, 40);

        B_consultas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_24px_1.png"))); // NOI18N
        B_consultas.setText("Consultas");
        B_consultas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_consultas.setContentAreaFilled(false);
        B_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_consultasActionPerformed(evt);
            }
        });
        getContentPane().add(B_consultas);
        B_consultas.setBounds(280, 90, 150, 40);

        B_modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_24px_1.png"))); // NOI18N
        B_modificar.setText("Modificar");
        B_modificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_modificar.setContentAreaFilled(false);
        B_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(B_modificar);
        B_modificar.setBounds(440, 90, 140, 40);

        tablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaGastos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 700, 500);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("28/04/2021");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(730, 810, 170, 30);

        Time.setBackground(new java.awt.Color(0, 153, 204));
        Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Time.setText("03:43 pm");
        Time.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(Time);
        Time.setBounds(900, 600, 140, 30);

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("12/05/2021");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(760, 600, 140, 30);

        P_buscar1.setBackground(new java.awt.Color(255, 255, 255));
        P_buscar1.setLayout(null);

        txtCodigoConsulta.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoConsulta.setText("Escribe el codigo del producto");
        txtCodigoConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoConsultaMouseClicked(evt);
            }
        });
        txtCodigoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoConsultaActionPerformed(evt);
            }
        });
        P_buscar1.add(txtCodigoConsulta);
        txtCodigoConsulta.setBounds(12, 5, 270, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_24px.png"))); // NOI18N
        jButton6.setText("Buscar");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        P_buscar1.add(jButton6);
        jButton6.setBounds(300, 5, 110, 30);

        jPanel2.add(P_buscar1);
        P_buscar1.setBounds(170, 570, 410, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 1050, 660);

        setSize(new java.awt.Dimension(743, 754));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volverMouseClicked
        // TODO add your handling code here:
        Punto_de_venta p= new Punto_de_venta();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_volverMouseClicked

    private void B_altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_altasActionPerformed
        // TODO add your handling code here:
        Altas_Gastos p= new Altas_Gastos();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_altasActionPerformed

    private void B_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_borrarActionPerformed
        try {
            int fila = tablaGastos.getSelectedRow();
            String cod = "";
            cod = tablaGastos.getValueAt(fila, 0).toString();
            
            int n = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de eliminar el registro? "+"ID: " + cod + ".?", "Confirmacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (n == JOptionPane.OK_OPTION) {
                
                PreparedStatement pst = cn.prepareStatement("DELETE FROM gasto WHERE idgasto ='" + cod + "'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "** Eliminado **");
                mostrardatos("");
//                btnBuscar.setText("");
                
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "** Seleccione un Producto Para Eliminar **");
        }  

    }//GEN-LAST:event_B_borrarActionPerformed
private int click;
    private void B_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_consultasActionPerformed
        // TODO add your handling code here:
              click++;
        if (click==1){
       P_buscar1.setVisible(true);
    
        }else{
              P_buscar1.setVisible(false);
              click=0;}
    }//GEN-LAST:event_B_consultasActionPerformed

    private void B_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_modificarActionPerformed
        // TODO add your handling code here:
        Gastos_Modificar p= new Gastos_Modificar();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_modificarActionPerformed
private int usuclick=0;
    private void txtCodigoConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoConsultaMouseClicked
        // TODO add your handling code here:
        txtCodigoConsulta.setForeground(new java.awt.Color(0,0,0));

        usuclick++;

        if (usuclick==1){

            txtCodigoConsulta.setText(null);

        }
    }//GEN-LAST:event_txtCodigoConsultaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    
        mostrardatos(txtCodigoConsulta.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtCodigoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoConsultaActionPerformed

    public void mostrardatos(String valor){
            TablaGastos obj = new TablaGastos();
            tablaGastos.setModel(obj.tabla(valor));   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_altas;
    private javax.swing.JButton B_borrar;
    private javax.swing.JButton B_consultas;
    private javax.swing.JButton B_modificar;
    private javax.swing.JLabel B_volver;
    private javax.swing.JPanel P_buscar1;
    private javax.swing.JLabel Time;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGastos;
    private javax.swing.JTextField txtCodigoConsulta;
    // End of variables declaration//GEN-END:variables
}
