/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexion.Conectar;
import Conexion.Conexion;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jasam
 */
public class Modificar_provedores extends javax.swing.JFrame {

    Conexion cc = new Conexion();
    Connection cin = cc.getConexion();
    PreparedStatement ps;
    static ResultSet rs;
    String nomTabla, sql;
    String mensaje, respuesta;
    boolean cliente, existencia;
    
    String HOST = "5000";
    int PUERTO = 5000;
        
    String IP1 = "192.168.0.102"; //Tabla provedores
    String IP2 = "192.168.0.103"; //Tabla Clientes
    String IP3 = "192.168.0.105";  // Tabla Inventario
    
    public Modificar_provedores() {
        initComponents();
        vertodo(); // Metodo que nos mostrara al inicio la tabla de Clientes
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modificar = new javax.swing.JPopupMenu();
        itemModificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        B_volver1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = 
        tablaProveedores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        itemModificar.setActionCommand("Modificar");
        itemModificar.setLabel("Modificar");
        itemModificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemModificarItemStateChanged(evt);
            }
        });
        itemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarActionPerformed(evt);
            }
        });
        Modificar.add(itemModificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modificar Provedor");

        B_volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volver1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_volver1)
                .addGap(300, 300, 300)
                .addComponent(jLabel1)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(B_volver1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1240, 82);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(250, 350, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 260, 150, 30);
        jPanel2.add(txtTelefono);
        txtTelefono.setBounds(250, 390, 200, 30);

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProveedores.setComponentPopupMenu(Modificar);
        jScrollPane1.setViewportView(tablaProveedores);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(460, 10, 770, 550);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_company_127px_1.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(160, 10, 130, 110);
        jPanel2.add(txtEmail);
        txtEmail.setBounds(10, 300, 430, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Direccion");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 440, 130, 30);
        jPanel2.add(txtDireccion);
        txtDireccion.setBounds(10, 480, 440, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ciudad");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 350, 130, 30);
        jPanel2.add(txtCiudad);
        txtCiudad.setBounds(10, 390, 200, 30);

        btnAlta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_24px_1.png"))); // NOI18N
        btnAlta.setText("Modificar Provedor");
        btnAlta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        btnAlta.setContentAreaFilled(false);
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlta);
        btnAlta.setBounds(110, 540, 230, 40);
        jPanel2.add(txtNombre);
        txtNombre.setBounds(10, 220, 430, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Provedor");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 170, 150, 40);
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(10, 140, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id del Provedor");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 100, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 1250, 690);

        setSize(new java.awt.Dimension(1260, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
           nomTabla = "proveedor"; // Definimos el nombre de la tabla
    int codigo = Integer.parseInt(txtCodigo.getText());
    comprobarTabla("SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME = '" + nomTabla + "'");
    
            if (existencia) {

            try {
             PreparedStatement pst = cin.prepareStatement("UPDATE " + nomTabla + " SET nombre='" 
                     + txtNombre.getText() + "',telefono='" + txtTelefono.getText() 
                     + "',email='" + txtEmail.getText() + "',ciudad='" + txtCiudad.getText() +
                     "',direccion='" + txtTelefono.getText() + "' WHERE id_proveedor='" 
                     + txtCodigo.getText() + "';");



                // Validamos el estado de la actualización
                int x = pst.executeUpdate();
                if (x > 0) {

                    // Mostramos de manera gráfica el resultado de la actualización 
                    JOptionPane.showMessageDialog(null, "Se actualizó correctarmente");
                    // Mostramos todos los datos de la tabla
                    sql = "SELECT * FROM " + nomTabla + " WHERE id_proveedor = '" + codigo + "'";
                    visualizar();

                    limpiar();
                }
            } catch (Exception e) {
                // Cualquier que la BDD arroje lo mostramos en un cuadro de dialogo
                JOptionPane.showMessageDialog(null, e, "Error al Modificar", JOptionPane.WARNING_MESSAGE);
            }

        } else {

            HOST = IP1; // Le pasamos la IP al HOST

            //Armamos la sentencia SQL de tipo actualización y se la pasamos al método que se comunicará con el servidor
            mensaje = "UPDATE " + nomTabla + " SET nombre='" 
                     + txtNombre.getText() + "',telefono='" + txtTelefono.getText() 
                     + "',email='" + txtEmail.getText() + "',ciudad='" + txtCiudad.getText() +
                     "',direccion='" + txtDireccion.getText() + "' WHERE id_proveedor='" 
                     + txtCodigo.getText() + "';";
            socketCliente();
            txtCodigo.setEditable(true);
            limpiar();
        }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void B_volver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volver1MouseClicked
        // TODO add your handling code here:
     Provedores p= new Provedores();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_volver1MouseClicked

    private void itemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Esta seguro de modificar los datos?", "Confirmar Modificación",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        int fila = tablaProveedores.getSelectedRow();
        if (fila >= 0) {
            txtCodigo.setText(tablaProveedores.getValueAt(fila, 0).toString());
            txtNombre.setText(tablaProveedores.getValueAt(fila, 1).toString());
            txtTelefono.setText(tablaProveedores.getValueAt(fila, 2).toString());
            txtEmail.setText(tablaProveedores.getValueAt(fila, 3).toString());
            txtCiudad.setText(tablaProveedores.getValueAt(fila, 4).toString());
            txtDireccion.setText(tablaProveedores.getValueAt(fila, 5).toString());
        } else {
            JOptionPane.showMessageDialog(null, "No selecciono fila");
        }

        }
    }//GEN-LAST:event_itemModificarActionPerformed

    private void itemModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemModificarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_itemModificarItemStateChanged

    
    public boolean consultar(String codigo){
        
        boolean cod = false;
        String sql = "SELECT * FROM proveedor WHERE id_proveedor='" + codigo + "'";


        try {
            Statement st = cin.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next()){
                cod =  true;
            }else{
                cod = false;
            }

            
        } catch (Exception ex) {
            System.out.print("Error"+ex);
        }    
        return cod;
    }

    public void limpiar(){
          txtCodigo.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtCiudad.setText("");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_provedores().setVisible(true);
            }
        });
    }

    
    
        
   public void visualizar() {

        ResultSet rs = null;
        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("ID Proveedores");
        dt.addColumn("Nombre");
        dt.addColumn("Telefono");
        dt.addColumn("Email");
        dt.addColumn("Ciudad");
        dt.addColumn("Direccion");
        tablaProveedores.setModel(dt);
        
        try {
            Object[] fila = new Object[6];
            Statement st = cin.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                fila[5] = rs.getString(6);

                dt.addRow(fila);
            }
            tablaProveedores.setModel(dt);
        } catch (Exception e) {
            System.out.println("*** Error al visualizar la tabla *** ");

        }

    }
   
   public void vertodo(){
       cliente = true; // Habilitamos una bandera
       nomTabla = "proveedor"; // Especificacmos el nombre de la tabla de la cual se requieren los datos
       
       comprobarTabla("SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME = '" + nomTabla + "'");
        if (existencia) {

            sql = "SELECT * FROM " + nomTabla + ";";  // Armamos la sentencia SQL
            
            visualizar(); // Método que muestra gráficammente la consulta

        } else {

            HOST = IP1; // Le pasamoa la IP al HOST con el cual se conectará el cliente
            mensaje = "SELECT * FROM " + nomTabla + ";"; // Armamos la sentencia SQL
            socketCliente(); // Llamamos el método que se encargará de la comunicación entre el cliente y el servidor
        }
   }
    
   public void socketCliente() {

        DefaultTableModel dt = new DefaultTableModel(); // Definimos una tabla temporal para guardar los datos

        dt.addColumn("ID Proveedores");
        dt.addColumn("Nombre");
        dt.addColumn("Telefono");
        dt.addColumn("Email");
        dt.addColumn("Ciudad");
        dt.addColumn("Direccion");


        String[] datos = new String[6]; // Declaramos un vector para guardar los datos

        // Creamos unas variables que nos ayudarán posteriormente
        int cont = 0, fin = 0;
        String aux = "";

        //Declaramos una variables especiales para los mensajes de entrada y salida
        DataInputStream in;  // para las instrucciones de entrada (seridor-cliente
        DataOutputStream out;   // para las instrucciones de salida (cliente-servidor)

        try {
            //Instacioamos la clase Socket, creamos un cliente que apunta a la IP y puerto del servidor
            Socket sc = new Socket(HOST, PUERTO); // dichos parámetros han sido espesificados anteriormente

            in = new DataInputStream(sc.getInputStream()); // variable que guarda los mensajes que manda el servidor (recibe)(respuesta)
            out = new DataOutputStream(sc.getOutputStream()); // variableque guarda los mensajes que le manda al servidor (manda)(peticion)

            out.writeUTF(mensaje); // manda mensaje al servidor (peticion)

            System.out.println("Mensaje del cliente: " + mensaje); // Muestro el mensaje enviado en la ventana de Output

            respuesta = in.readUTF(); // recibe el mensaje del servidor (respuesta)
            System.out.println("Respuesta del servidor: " + respuesta); // Muestro el mensaje

            if ((respuesta.contains("Conectado")) || respuesta.contains("Desconectado") || respuesta.contains("Se") || respuesta.contains("Ha")) {
                if (respuesta.contains("insertó")) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");


                } else {
                    if (respuesta.contains("actualizó")) {
                        JOptionPane.showMessageDialog(null, "Registro Actualizado");


                    } else {
                        if (respuesta.contains("Elimino")) {
                            JOptionPane.showMessageDialog(null, "Registro Eliminado");
                        } else {

                        }
                    }
                }

            } else {
                if (respuesta.equals("(0)")) {

                } else {

                    fin = respuesta.lastIndexOf(",");
                    cont = Integer.parseInt(respuesta.substring(1, 2));
                    respuesta = respuesta.substring(3, fin + 1);
                                            for (int x = 1; x <= cont; x++) {
                        separarRegistros(dt, datos);
                    }
                }
            }

            if (respuesta.equals("")) {
                sc.close();
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Servidor no encontrado - Verifique la dirección IP", "Error", JOptionPane.WARNING_MESSAGE);
        }

        cliente = false;
    }
   
   public void comprobarTabla(String sql) {
        try {
            Statement q = cin.createStatement();
            ResultSet w = q.executeQuery(sql);

            String[] consulta = new String[1];
            String aux = "";

            while (w.next()) {
                // codigo
                aux = consulta[0] = w.getString(1);
            }

            if (aux.isEmpty()) {
                existencia = false;
            } else {
                existencia = true;
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.WARNING_MESSAGE);
            System.out.println("Error al comprobar existencia" + ex);
        }
    }
   
       public String segmentar(String aux, DefaultTableModel modelo, String[] datos) {
        int columna = 0, registro = 0, ultimo;
        String col = "", col2 = "";

        try {
            columna = aux.indexOf(" ");
            registro = aux.indexOf(",");
            ultimo = aux.lastIndexOf(",");
            //   System.out.println("ultimo: " +ultimo);
            //   System.out.println("tamaño: " +aux.length());

            //   System.out.println("registro: " +registro);
            col = aux.substring(0, columna);
            col2 = aux.substring(columna + 1, registro);

            //  System.out.println("Columna 1: " + col);
            //  System.out.println("Columna 2: " + col2);
            //   MostrarTabla2(col, col2);
            datos[0] = col;
            //   System.out.println("columna1: " + col);
            datos[1] = col2;
            //   System.out.println("columna2: " + col2);
            modelo.addRow(datos);

            aux = aux.substring(registro + 1, aux.length());

            //segmentar(aux);
        } catch (Exception e) {

        }
        return aux;
    }

    public void separarRegistros(DefaultTableModel modelo, String[] datos) {
        String registro = "";
        int inicio = respuesta.indexOf(",");
        int fin = respuesta.lastIndexOf(",");
        registro = respuesta.substring(0, inicio);
        respuesta = respuesta.substring(inicio + 1, respuesta.length());

        separarColumnas(registro, modelo, datos);

    }

    public void separarColumnas(String registro, DefaultTableModel modelo, String[] datos) {
        char[] vector = new char[registro.length()];
        String aux, col;
        int cont = 0;

        //  System.out.println("repuesta " + registro);
        for (int x = 0; x < registro.length(); x++) {
            aux = String.valueOf(vector[x] = registro.charAt(x));
            if (aux.equals("*")) {
                cont++;
            }
        }

        int[] vector2 = new int[cont];
        String[] valores = new String[cont];

        int c = 0;
        for (int x = 0; x < registro.length(); x++) {
            aux = String.valueOf(vector[x] = registro.charAt(x));
            if (aux.equals("*")) {

                vector2[c] = x;

            }
        }
        String aux2;
        for (int y = 0; y < cont; y++) {
            int inicio = registro.indexOf("*");
            aux2 = registro.substring(0, inicio);
            registro = registro.substring(inicio + 1, registro.length());

            // System.out.println("aux2: " +aux2);
            datos[y] = aux2;

            if (y == (cont - 1)) {
                //        System.out.println("a: " +registro);
                datos[y + 1] = registro;
            }

        }

        modelo.addRow(datos);
        tablaProveedores.setModel(modelo);

    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_volver1;
    private javax.swing.JPopupMenu Modificar;
    private javax.swing.JButton btnAlta;
    private javax.swing.JMenuItem itemModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
