/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author jasam
 */
public class Olvidaste_contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Crear_usuario
     */
    public Olvidaste_contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        B_volver = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        B_Re = new javax.swing.JLabel();
        B_Cancel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ayuda de la cuenta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 10, 360, 60);

        B_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volverMouseClicked(evt);
            }
        });
        getContentPane().add(B_volver);
        B_volver.setBounds(10, 10, 60, 60);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Escribe tu nombre de usuario y tu palabra de seguridad para ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 80, 470, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("restablecer tu contraseña.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 100, 190, 21);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de usuario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 240, 160, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_lock_100px.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 120, 100, 110);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 240, 190, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 310, 190, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Palabra de seguridad");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 310, 150, 30);

        B_Re.setBackground(new java.awt.Color(0, 0, 0));
        B_Re.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        B_Re.setForeground(new java.awt.Color(255, 255, 255));
        B_Re.setText("   Recuperar");
        B_Re.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        B_Re.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_ReMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_ReMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_ReMouseExited(evt);
            }
        });
        getContentPane().add(B_Re);
        B_Re.setBounds(350, 380, 100, 40);

        B_Cancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        B_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        B_Cancel.setText("     Cancelar");
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        B_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_CancelMouseExited(evt);
            }
        });
        getContentPane().add(B_Cancel);
        B_Cancel.setBounds(200, 380, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 610);

        setSize(new java.awt.Dimension(495, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volverMouseClicked
        // TODO add your handling code here:
            Inicio_de_sesion p= new Inicio_de_sesion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_volverMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void B_ReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ReMouseClicked
        // TODO add your handling code here:
         Recuperacion_contraseña p= new Recuperacion_contraseña();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_ReMouseClicked

    private void B_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseClicked
        // TODO add your handling code here:
           Inicio_de_sesion p= new Inicio_de_sesion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_CancelMouseClicked

    private void B_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseEntered
        // TODO add your handling code here:
        B_Cancel.setForeground(new java.awt.Color(255, 0, 51));
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        B_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_B_CancelMouseEntered

    private void B_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseExited
        // TODO add your handling code here:
         B_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_B_CancelMouseExited

    private void B_ReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ReMouseEntered
        // TODO add your handling code here:
        B_Re.setForeground(new java.awt.Color(255, 0, 51));
        B_Re.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        B_Re.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_B_ReMouseEntered

    private void B_ReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ReMouseExited
        // TODO add your handling code here:
          B_Re.setForeground(new java.awt.Color(255, 255, 255));
        B_Re.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_B_ReMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olvidaste_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olvidaste_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olvidaste_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olvidaste_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olvidaste_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_Cancel;
    private javax.swing.JLabel B_Re;
    private javax.swing.JLabel B_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
