/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import Conexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jasam
 */
public class Provedores extends javax.swing.JFrame {

    /**
     * Creates new form Almacen
     */
    public Provedores() {
        initComponents();
           P_buscar.setVisible(false);
           DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
Runnable runnable = new Runnable() {
    @Override
    public void run() {
        while (true) {
            try {
                Thread.sleep(500);
                Time.setText("Hora "+formateador.format(LocalDateTime.now()));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
};
Thread hilo = new Thread(runnable);
hilo.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_consultas = new javax.swing.JButton();
        B_borrar = new javax.swing.JButton();
        B_altas = new javax.swing.JButton();
        B_modificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        P_buscar = new javax.swing.JPanel();
        T_Con = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        B_volver = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        B_consultas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_24px_1.png"))); // NOI18N
        B_consultas.setText("Consultas");
        B_consultas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_consultas.setContentAreaFilled(false);
        B_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_consultasActionPerformed(evt);
            }
        });
        getContentPane().add(B_consultas);
        B_consultas.setBounds(290, 90, 150, 40);

        B_borrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delete_48px.png"))); // NOI18N
        B_borrar.setText("Borrar");
        B_borrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_borrar.setContentAreaFilled(false);
        B_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_borrarActionPerformed(evt);
            }
        });
        getContentPane().add(B_borrar);
        B_borrar.setBounds(150, 90, 130, 40);

        B_altas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_altas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_24px.png"))); // NOI18N
        B_altas.setText("Altas");
        B_altas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_altas.setContentAreaFilled(false);
        B_altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_altasActionPerformed(evt);
            }
        });
        getContentPane().add(B_altas);
        B_altas.setBounds(10, 90, 130, 40);

        B_modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_24px_1.png"))); // NOI18N
        B_modificar.setText("Modificar");
        B_modificar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        B_modificar.setContentAreaFilled(false);
        B_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(B_modificar);
        B_modificar.setBounds(450, 90, 140, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Provedor", "Nombre del Provedor", "Email", "Telefono", "Direccion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 1020, 520);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("28/04/2021");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(730, 810, 170, 30);

        Time.setBackground(new java.awt.Color(0, 153, 204));
        Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Time.setText("03:43 pm");
        Time.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(Time);
        Time.setBounds(900, 600, 140, 30);

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("12/05/2021");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(760, 600, 140, 30);

        P_buscar.setBackground(new java.awt.Color(255, 255, 255));
        P_buscar.setLayout(null);

        T_Con.setForeground(new java.awt.Color(153, 153, 153));
        T_Con.setText("Escribe el codigo del producto");
        T_Con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_ConMouseClicked(evt);
            }
        });
        P_buscar.add(T_Con);
        T_Con.setBounds(12, 5, 270, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_24px.png"))); // NOI18N
        jButton5.setText("Buscar");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        P_buscar.add(jButton5);
        jButton5.setBounds(300, 5, 110, 30);

        jPanel2.add(P_buscar);
        P_buscar.setBounds(170, 590, 410, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 1050, 660);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Provedores");

        B_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(B_volver)
                .addGap(335, 335, 335)
                .addComponent(jLabel1)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B_volver))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 80);

        setSize(new java.awt.Dimension(1064, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private int click;
    private void B_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_consultasActionPerformed
        // TODO add your handling code here:
             click++;
        if (click==1){
       P_buscar.setVisible(true);
    
        }else{
              P_buscar.setVisible(false);
              click=0;
        }
    }//GEN-LAST:event_B_consultasActionPerformed

    private void B_altasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_altasActionPerformed
        // TODO add your handling code here:
         Altas_Provedores p= new Altas_Provedores();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_altasActionPerformed

    private void B_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_modificarActionPerformed
        // TODO add your handling code here:
        Modificar_provedores p= new Modificar_provedores();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_modificarActionPerformed

    private void B_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volverMouseClicked
        // TODO add your handling code here:
 Punto_de_venta p= new Punto_de_venta();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_volverMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            consulta();
    }//GEN-LAST:event_jButton5ActionPerformed
private int usuclick =0;
    private void T_ConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_ConMouseClicked
        // TODO add your handling code here:
        T_Con.setForeground(new java.awt.Color(0, 0, 0));

        usuclick++;

        if (usuclick == 1) {

            T_Con.setText(null);

        }
    }//GEN-LAST:event_T_ConMouseClicked

    private void B_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_borrarActionPerformed
        eliminar();
    }//GEN-LAST:event_B_borrarActionPerformed

     public void consulta() {
        Conectar cc = new Conectar();
        Connection cn = cc.conexion();

        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("IdProveedor");
        dt.addColumn("Nombre");
        dt.addColumn("Telefono");
        dt.addColumn("Email");
        dt.addColumn("Ciudad");
        jTable1.setModel(dt);

        try {
            ResultSet rs = null;
            Object[] fila = new Object[5];
            Statement st = cn.createStatement();

            rs = st.executeQuery("SELECT * FROM provedor WHERE idProvedor = '" + T_Con.getText() + "'");

            if (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                dt.addRow(fila);
            } else {
                JOptionPane.showMessageDialog(null, "*** El Proveedor que busca no se encuentra registrado ***");
            }
            jTable1.setModel(dt);

        } catch (Exception e) {
            System.out.println("*** Error al visualizar la tabla  *** ");

        }

    }
    
    
    public void eliminar() {
        try {
            // Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/ventadecoches?user=root&password=");
            Conectar cc = new Conectar();
            Connection cn = cc.conexion();
            int fila = jTable1.getSelectedRow();
            String cod = "";
            cod = jTable1.getValueAt(fila, 0).toString();
            
            int n = JOptionPane.showConfirmDialog(null, "¿ Esta Seguro de eliminar a " + cod + ".?", "Confirmacion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (n == JOptionPane.OK_OPTION) {
                
                PreparedStatement pst = cn.prepareStatement("DELETE FROM provedor WHERE idProvedor ='" + cod + "'");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "** Eliminado **");
                visualizar();
                T_Con.setText("");
                
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "** Seleccione un Proveedor Para Eliminar **");
        }
        
    }
    
    public void visualizar(){
       Conectar cc = new Conectar();
        Connection cn = cc.conexion();

        DefaultTableModel dt = new DefaultTableModel();
        dt.addColumn("IdProveedor");
        dt.addColumn("Nombre");
        dt.addColumn("Telefono");
        dt.addColumn("Email");
        dt.addColumn("Ciudad");
        jTable1.setModel(dt);

        try {
            ResultSet rs = null;
            Object[] fila = new Object[5];
            Statement st = cn.createStatement();

            rs = st.executeQuery("SELECT * FROM provedor ");

            while (rs.next()) {
                fila[0] = rs.getString(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getString(4);
                fila[4] = rs.getString(5);
                dt.addRow(fila);
            } 
            jTable1.setModel(dt);
        } catch (Exception e) {
            System.out.println("*** Error al visualizar la tabla  *** ");

        }

    
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_altas;
    private javax.swing.JButton B_borrar;
    private javax.swing.JButton B_consultas;
    private javax.swing.JButton B_modificar;
    private javax.swing.JLabel B_volver;
    private javax.swing.JPanel P_buscar;
    private javax.swing.JTextField T_Con;
    private javax.swing.JLabel Time;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
