/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author jasam
 */
public class Recuperacion_contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Crear_usuario
     */
    public Recuperacion_contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        B_volver = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        B_Recu = new javax.swing.JLabel();
        B_Cancel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gotham Thin", 0, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Restablecer la contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 10, 400, 60);

        B_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volverMouseClicked(evt);
            }
        });
        getContentPane().add(B_volver);
        B_volver.setBounds(10, 10, 60, 60);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nueva contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 160, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 210, 190, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 290, 190, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vuelve a escribir la");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 280, 150, 30);

        B_Recu.setBackground(new java.awt.Color(0, 0, 0));
        B_Recu.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        B_Recu.setForeground(new java.awt.Color(255, 255, 255));
        B_Recu.setText("   Recuperar");
        B_Recu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        B_Recu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_RecuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_RecuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_RecuMouseExited(evt);
            }
        });
        getContentPane().add(B_Recu);
        B_Recu.setBounds(320, 360, 100, 40);

        B_Cancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        B_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        B_Cancel.setText("     Cancelar");
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        B_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_CancelMouseExited(evt);
            }
        });
        getContentPane().add(B_Cancel);
        B_Cancel.setBounds(180, 360, 100, 40);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("contraseña");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 100, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_padlock_100px_1.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 70, 100, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 610);

        setSize(new java.awt.Dimension(483, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volverMouseClicked
        // TODO add your handling code here:
             Olvidaste_contraseña p= new  Olvidaste_contraseña();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_volverMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void B_RecuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RecuMouseClicked
        // TODO add your handling code here:
         Inicio_de_sesion p= new Inicio_de_sesion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_RecuMouseClicked

    private void B_CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseClicked
        // TODO add your handling code here:
         Inicio_de_sesion p= new Inicio_de_sesion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_CancelMouseClicked

    private void B_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseEntered
        // TODO add your handling code here:
        B_Cancel.setForeground(new java.awt.Color(255, 0, 51));
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        B_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_B_CancelMouseEntered

    private void B_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CancelMouseExited
        // TODO add your handling code here:
         B_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        B_Cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_B_CancelMouseExited

    private void B_RecuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RecuMouseEntered
        // TODO add your handling code here:
        B_Recu.setForeground(new java.awt.Color(255, 0, 51));
        B_Recu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        B_Recu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_B_RecuMouseEntered

    private void B_RecuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RecuMouseExited
        // TODO add your handling code here:
          B_Recu.setForeground(new java.awt.Color(255, 255, 255));
        B_Recu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_B_RecuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuperacion_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuperacion_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_Cancel;
    private javax.swing.JLabel B_Recu;
    private javax.swing.JLabel B_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
