/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;
import br.com.adilson.util.Extenso;
import br.com.adilson.util.PrinterMatrix;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.text.DecimalFormat;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.SimpleDoc;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import Conexion.Conectar;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;

import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;


/**
 *
 * @author jasam
 */
public class Ventas extends javax.swing.JFrame {
DefaultTableModel dt = new DefaultTableModel();
    /**
     * Creates new form Ventas
     */
    int respuesta;
    public Ventas() {
        setLocationRelativeTo(null);
        initComponents();
        asignarfecha();
     LocalTime hora = LocalTime.now();
     String horaActual = String.valueOf(hora);
     labelHora.setText(horaActual);
     labelFecha.setText(asignarfecha());
     generaSerie();
    }

     Conectar cc = new Conectar();
     Connection cn = cc.conexion(); 
     final String inventario = "[192.168.5.183].purificadora.dbo.inventario";
     ResultSet rs = null;
     PreparedStatement ps;
     Validar valida = new Validar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        PoElimina = new javax.swing.JPopupMenu();
        eliminar = new javax.swing.JMenuItem();
        txtVendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        labelNombre = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtDescrip = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        B_volver = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TotalaPagar = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecio1 = new javax.swing.JTextField();
        btnMas = new javax.swing.JButton();
        Total4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cambio = new javax.swing.JLabel();
        Total5 = new javax.swing.JLabel();
        Total3 = new javax.swing.JLabel();
        txtImprime = new javax.swing.JButton();
        btnNuevaVenat = new javax.swing.JButton();

        jLabel18.setText("jLabel18");

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        PoElimina.add(eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setModalExclusionType(null);
        setPreferredSize(new java.awt.Dimension(1230, 860));
        getContentPane().setLayout(null);

        txtVendedor.setForeground(new java.awt.Color(204, 204, 204));
        txtVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(txtVendedor);
        txtVendedor.setBounds(150, 150, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VENDEDOR:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 160, 120, 22);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(1240, 860));
        jPanel1.setPreferredSize(new java.awt.Dimension(1230, 768));
        jPanel1.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 560, 310, 120);

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });
        jPanel1.add(txtSerie);
        txtSerie.setBounds(680, 90, 90, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SERIE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(610, 90, 70, 30);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("FACTURA");
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(610, 140, 120, 31);

        labelNombre.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(51, 51, 51));
        labelNombre.setText("   Purificadora Agua inmaculada");
        labelNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labelNombre);
        labelNombre.setBounds(300, 100, 280, 40);

        labelDireccion.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        labelDireccion.setText("       Colonia centro numero 5");
        labelDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labelDireccion);
        labelDireccion.setBounds(300, 160, 280, 40);

        labelStok.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelStok.setForeground(new java.awt.Color(255, 255, 255));
        labelStok.setText("Costo");
        jPanel1.add(labelStok);
        labelStok.setBounds(1100, 260, 110, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CLIENTE:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 100, 110, 30);

        txtCliente.setForeground(new java.awt.Color(204, 204, 204));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCliente);
        txtCliente.setBounds(150, 100, 110, 30);

        txtDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescrip);
        txtDescrip.setBounds(200, 290, 210, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CODIGO");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 260, 110, 30);

        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtImporteKeyPressed(evt);
            }
        });
        jPanel1.add(txtImporte);
        txtImporte.setBounds(540, 670, 110, 30);

        txtCantidad.setForeground(new java.awt.Color(204, 204, 204));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad);
        txtCantidad.setBounds(510, 290, 110, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cant:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(540, 260, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Precio:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(770, 260, 110, 30);

        jButton4.setText("Agregar producto ala lista");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(450, 340, 200, 23);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(247, 239, 239))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 330, 1190, 60);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(247, 239, 239))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 70, 1190, 150);

        tablaVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Piezas", "Costo"
            }
        ));
        tablaVentas.setComponentPopupMenu(PoElimina);
        jScrollPane1.setViewportView(tablaVentas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 400, 1140, 200);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripcion");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(200, 260, 110, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTA DE PRODUCTOS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(520, 20, 290, 33);

        jButton1.setText("Confirmar Venta");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 610, 160, 30);

        jButton2.setText("Buscar Articulo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 610, 160, 30);

        jButton3.setText("Cancelar Venta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(520, 610, 140, 30);

        Total.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("$");
        jPanel1.add(Total);
        Total.setBounds(990, 640, 80, 80);

        labelFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelFecha.setText("28/04/2021");
        labelFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labelFecha);
        labelFecha.setBounds(910, 710, 170, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Usuario: Admin");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel20);
        jLabel20.setBounds(1020, 810, 210, 30);

        labelHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHora.setText("06:18 pm");
        labelHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(labelHora);
        labelHora.setBounds(1080, 710, 120, 30);

        B_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_go_back_60px_1.png"))); // NOI18N
        B_volver.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        B_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_volverMouseClicked(evt);
            }
        });
        jPanel1.add(B_volver);
        B_volver.setBounds(30, 0, 60, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Importe:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(450, 670, 110, 30);

        TotalaPagar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TotalaPagar.setForeground(new java.awt.Color(255, 255, 255));
        TotalaPagar.setText("00");
        jPanel1.add(TotalaPagar);
        TotalaPagar.setBounds(1020, 620, 210, 120);

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCodigo);
        txtCodigo.setBounds(50, 290, 110, 30);

        txtPrecio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio1ActionPerformed(evt);
            }
        });
        txtPrecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecio1KeyPressed(evt);
            }
        });
        jPanel1.add(txtPrecio1);
        txtPrecio1.setBounds(1070, 290, 110, 30);

        btnMas.setText("Nuevo Producto");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMas);
        btnMas.setBounds(670, 610, 150, 30);

        Total4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Total4.setForeground(new java.awt.Color(255, 255, 255));
        Total4.setText("Total");
        jPanel1.add(Total4);
        Total4.setBounds(940, 640, 80, 80);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });
        jPanel1.add(txtPrecio);
        txtPrecio.setBounds(740, 290, 110, 30);

        cambio.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cambio.setForeground(new java.awt.Color(255, 255, 255));
        cambio.setText("00");
        jPanel1.add(cambio);
        cambio.setBounds(820, 640, 110, 80);

        Total5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Total5.setForeground(new java.awt.Color(255, 255, 255));
        Total5.setText("Cambio");
        jPanel1.add(Total5);
        Total5.setBounds(720, 640, 80, 80);

        Total3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Total3.setForeground(new java.awt.Color(255, 255, 255));
        Total3.setText("$");
        jPanel1.add(Total3);
        Total3.setBounds(790, 640, 80, 80);

        txtImprime.setText("Imprimir Comprobante");
        txtImprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImprimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtImprime);
        txtImprime.setBounds(1020, 610, 150, 30);

        btnNuevaVenat.setText("Nueva Venta");
        btnNuevaVenat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVenatActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaVenat);
        btnNuevaVenat.setBounds(830, 610, 150, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 870);

        setSize(new java.awt.Dimension(1254, 891));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendedorActionPerformed

    private void txtDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void B_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_volverMouseClicked
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_B_volverMouseClicked
private int usuclick =0;
    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        // TODO add your handling code here:
            txtCantidad.setForeground(new java.awt.Color(0,0,0));

         usuclick++;
     
        if (usuclick==1){
                      
        
            txtCantidad.setText(null);

      
        }
    }//GEN-LAST:event_txtCantidadMouseClicked
    private int pclick = 0;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if ( txtCodigo.getText().equals("") || txtDescrip.getText().equals("") || txtPrecio.getText().equals("") || txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Verifique que no haya campos vacios");
        } else 
            RegisTabla();   

    }//GEN-LAST:event_jButton4ActionPerformed

   
    
    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3AncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Almacen alm = new Almacen();
      alm.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
   
        
        try{
    DefaultTableModel dtm = (DefaultTableModel) tablaVentas.getModel(); //TableProducto es el nombre de mi tabla ;)
    dtm.removeRow(tablaVentas.getSelectedRow()); 
    sumar();
   }catch(Exception e){
       System.out.println(e.toString());
   }
       
    }//GEN-LAST:event_eliminarActionPerformed

    private void txtImporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyPressed
  
    }//GEN-LAST:event_txtImporteKeyPressed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCodigo.getText())) {
                consulta();
            }

        }

   
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtPrecio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1ActionPerformed

    private void txtPrecio1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecio1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio1KeyPressed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
      txtCodigo.setText("");
        txtCantidad.setText("");
        txtDescrip.setText("");
        txtImporte.setText("");
        txtPrecio.setText("");
        txtPrecio1.setText("");
        Total.setText("");
       
    }//GEN-LAST:event_btnMasActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

            limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float importe;
        int cantidad; 
        if (txtImporte.getText().equals("") || txtCodigo.getText().equals("") || txtVendedor.getText().equals("")
                || txtCliente.getText().equals("") || txtDescrip.getText().equals("") || txtPrecio1.getText().equals("")
                || txtPrecio.getText().equals("") ||txtCantidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor Verifique que no haya campos vacios");
        } else {
         
            recorre();
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtImprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImprimeActionPerformed
          imprimirTicket(tablaVentas, "10", TotalaPagar.getText(), txtImporte.getText(), cambio.getText());
          JOptionPane.showMessageDialog(null,"Factura Impresa Correctamente");
    }//GEN-LAST:event_txtImprimeActionPerformed

    private void btnNuevaVenatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVenatActionPerformed
        limpiar();
        generaSerie();
    }//GEN-LAST:event_btnNuevaVenatActionPerformed
    
   public void RegisTabla(){ 
        int cam = 0;
        int cantidad = 0;
        int cod = 0;
        try {
            cod = Integer.parseInt(txtCodigo.getText());
            Statement st = cn.createStatement();
            rs = st.executeQuery("SELECT cantidad FROM inventario WHERE idproducto = " + cod + " ");
            if (rs.next()) {
                cam = Integer.parseInt(rs.getString(1));
               cantidad =  valida.esInt(txtCantidad.getText());
            }
            if (cantidad > cam) {

                JOptionPane.showMessageDialog(null, "Cantida insuficiente solo " + cam + " En existencia ");
            } else {
                String[] titulo = new String[]{"Codigo", "Descrpcion", "Piezas", "Costo"};
                dt.setColumnIdentifiers(titulo);
                tablaVentas.setModel(dt);
                MostraYconsulta();
                sumar();
            }
        } catch (Exception ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            
        }

   
   }
    
    
    public void sumar() {
        double sumatoria = 0;
        double sumatoria1 = 0;
        int totalRow = tablaVentas.getRowCount();
        totalRow -= 1;
        for (int i = 0; i <= (totalRow); i++) {
            sumatoria = Double.parseDouble(String.valueOf(tablaVentas.getValueAt(i, 3)));
            sumatoria1 = sumatoria1 + sumatoria;
        }

        TotalaPagar.setText(String.valueOf(sumatoria1));

    }
    
    public void actualizarStok(int id, int stock) {
        String sql = "update "+inventario+" set cantidad = ? where idproducto = "+id;
        try {
             // JOptionPane.showMessageDialog(null, id+"P"+stock);
            ps = cn.prepareStatement(sql);
            ps.setInt(1, stock);
           // ps.setInt(2, id);
            ps.executeUpdate();

        } catch (Exception e) {
            System.out.println(e.toString());
        }
      
    }

       public void recorre() {
        float cambi = 0,importe = 0,total = 0;
        int cam = 0,cant;
        int cod = 0;
        int sa = 0;
        for (int i = 0; i < tablaVentas.getRowCount(); i++) {
            cod = Integer.parseInt(tablaVentas.getValueAt(i, 0).toString());
        cant = Integer.parseInt(tablaVentas.getValueAt(i, 2).toString());
        importe = valida.esFloat(txtImporte.getText());
        total = valida.esFloat(TotalaPagar.getText()); 
        cambi = importe-total;
             if(importe<total){
            JOptionPane.showMessageDialog(null, "Importe Insuficiente");
        }else{
              try {
                Statement st = cn.createStatement();
                rs = st.executeQuery("SELECT cantidad FROM " +inventario+ " WHERE idproducto = " + cod + "");
                if (rs.next()) {
                    cam = Integer.parseInt(rs.getString(1));
                    sa = cam - cant;
                         importe = valida.esFloat(txtImporte.getText());
                         total = valida.esFloat(TotalaPagar.getText()); 
                    actualizarStok(cod, sa);
                   
                }
            } catch (SQLException ex) {
                Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
            }
             registraVentas();
              cambio.setText(String.valueOf(cambi));
             }
           
        }

       
      
         
    }
    
    
    public void limpiar() {
        DefaultTableModel modelo=(DefaultTableModel) tablaVentas.getModel();
            int filas=tablaVentas.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        txtCodigo.setText("");
        txtCantidad.setText("");
        txtDescrip.setText("");
        txtImporte.setText("");
        txtPrecio.setText("");
        txtPrecio1.setText("");
        txtPrecio1.setText("");
        Total.setText("");
        cambio.setText("$ 00");
        TotalaPagar.setText("$ 00");

    }

    public void consulta() {
        int id;
        DefaultTableModel dt = new DefaultTableModel();
        try {

            Statement st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM "+inventario+" WHERE idproducto = '" + txtCodigo.getText() + "'");
            if (rs.next()) {
                txtDescrip.setText(rs.getString(2));
                txtPrecio.setText(rs.getString(4));

            } else {
                JOptionPane.showMessageDialog(null, "*** El ID que Ingreso es Invalido o el Prodicto no esta Registrado  ***");
            }

            //tabla.setRowHeight(70);
        } catch (Exception e) {
            System.out.println("*** Error al visualizar la tabla *** ");

        }

    }

    public void registraVentas() {
        String sql = "INSERT INTO venta (idventa, fecha, totalventa, direccion, usuario_idusuario,cliente_idcliente) values (?,?,?,?,?,?)";
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, txtSerie.getText());
            ps.setString(2, labelFecha.getText());
            ps.setString(3, TotalaPagar.getText());
            ps.setString(4, labelDireccion.getText());
            ps.setString(5, txtVendedor.getText());
            ps.setString(6, txtCliente.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null,"Venta Efectuada con Exito ");
        } catch (SQLException e) {
            System.out.println(e.toString());

        }

    }

    public void MostraYconsulta() {

        int existe = 0, cant = 0;
        float precio, total;

        try {
           
            cant = Integer.parseInt(txtCantidad.getText());
            precio = Integer.parseInt(txtPrecio.getText());
           
            precio = precio * cant;

            String precio2 = String.valueOf(precio);
            txtPrecio1.setText(precio2);
            try {
                dt.addRow(new Object[]{
                    txtCodigo.getText(),
                    txtDescrip.getText(),
                    txtCantidad.getText(),
                    txtPrecio1.getText()
                });

            } catch (Exception e) {
                System.out.println("Error");

            }

            //tabla.setRowHeight(70);
        } catch (Exception e) {
            System.out.println("*** Error al visualizar la tabla *** ");

        }

    }

   

    public static String asignarfecha() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatoFecha.format(fecha);
    }

    public String nroSerie() {
        String serie = "";
        String sql = "SELECT max(idventa) from venta";
        try {
            Conectar cc = new Conectar();
            Connection cn = cc.conexion();
            ResultSet rs;
            PreparedStatement ps;

            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                serie = rs.getString(1);
            }

        } catch (Exception e) {
            System.out.println("Error de Conexion");

        }
        return serie;
    }

    public void generaSerie() {
        String serie = nroSerie();
        if (serie == null) {
            txtSerie.setText("00001");
            txtCliente.setText("001");
            txtVendedor.setText("4500");

        } else {
            int increment = Integer.parseInt(serie);
            increment = increment + 1;
            txtSerie.setText("00000" + increment);
        }

    }

    public String eligeRuta() {
        JFileChooser f = new JFileChooser();
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showSaveDialog(null);
        String ruta = String.valueOf(f.getSelectedFile());
        return ruta;
    }


void imprimirTicket(JTable jtbl_venta, String subTotal, String total, String dineroR, String devolucion){
try {
    
    
     String ruta = eligeRuta();
    PrinterMatrix printer = new PrinterMatrix();
    Extenso e = new Extenso();

    e.setNumber(20.30);
    int filas = jtbl_venta.getRowCount();
    int tamaño = filas+40;
    printer.setOutSize(tamaño, 80);
    printer.printTextWrap(0, 1, 5, 80, "===========================================================");
    printer.printTextWrap(1, 1, 35, 80, labelNombre.getText()); //Nombre establecimiento
    printer.printTextWrap(3, 1, 31, 80, labelDireccion.getText()); //Barrio
    printer.printTextWrap(6, 1, 10, 41,"Fecha "+ labelFecha.getText()); //Aqui va la fecha de recibo
    printer.printTextWrap(6, 1, 38, 80,"Hora " + labelHora.getText()); //Aqui va la hora de recibo
    printer.printTextWrap(7, 1, 3, 80, "Numero "+ txtSerie.getText()); //Numero del recibo - FACTURA O PEDIDO
    printer.printTextWrap(8, 1, 3, 80, "Atiende "+txtVendedor.getText()); //Nombre Cajero
    printer.printTextWrap(9, 1, 3, 80, "Cliente "+txtCliente.getText());//Nombre del Cliente
    printer.printTextWrap(10,1, 5, 80, "——————————–——-—————–——–———–——–———–——–———");
    printer.printTextWrap(11,1, 7, 80, "ID   DESCRIPCION                        CANT           PRECIO");
    printer.printTextWrap(12,1, 0, 80, " ");

    for (int i = 0; i < filas; i++) {
        int p = 13+i; //Fila

        printer.printTextWrap(p , 1, 7, 19 , jtbl_venta.getValueAt(i,0).toString());
        printer.printTextWrap(p , 1, 12, 42 , jtbl_venta.getValueAt(i,1).toString());
        printer.printTextWrap(p , 1, 47, 49, jtbl_venta.getValueAt(i,2).toString());

        String pre= printer.alinharADireita(10, jtbl_venta.getValueAt(i,3).toString());
        printer.printTextWrap(p , 1, 57, 80, pre);

        //String inp= printer.alinharADireita(7,punto_Venta.jtbl_venta.getValueAt(i,6).toString());
        //printer.printTextWrap(p , 1, 25, 32, inp);
    }
    DecimalFormat formateador = new DecimalFormat("#.###");

    String tot= printer.alinharADireita(10, total);
    printer.printTextWrap(filas+18, 1, 5, 80, "Total a pagar: ");
    printer.printTextWrap(filas+18, 1, 20, 80, "$"+TotalaPagar.getText());

    String efe= printer.alinharADireita(10,dineroR);
    printer.printTextWrap(filas+19, 1, 5, 80, "Efectivo : ");
    printer.printTextWrap(filas+19, 1, 20, 80, "$"+txtImporte.getText());

    String cam= printer.alinharADireita(10,devolucion);
    printer.printTextWrap(filas+20, 1, 5, 80, "Cambio : ");
    printer.printTextWrap(filas+20, 1, 20, 80, "$"+ cambio.getText());

    printer.printTextWrap(filas+21, 1, 5, 80, "——————————–——————-----——–———–——–—–———–——–———");
    printer.printTextWrap(filas+22, 1, 26,80, "!Gracias por su preferencia!");
    printer.printTextWrap(filas+26, 1, 5,80, "================================================================");



    printer.toFile(ruta+"\\impresion.txt");
    FileInputStream inputStream = null;

    try {
        inputStream = new FileInputStream(ruta+"\\impresion.txt");
    } catch (FileNotFoundException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al guardar");
    }
    if (inputStream == null) {
        return;
    }

    DocFlavor docFormat = DocFlavor.INPUT_STREAM.AUTOSENSE;
    Doc document = new SimpleDoc(inputStream, docFormat, null);
    PrintRequestAttributeSet attributeSet = new HashPrintRequestAttributeSet();
    PrintService defaultPrintService = PrintServiceLookup.lookupDefaultPrintService();

    if (defaultPrintService != null) {
        DocPrintJob printJob = defaultPrintService.createPrintJob();
        try {
            printJob.print(document, attributeSet);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    } else {
        System.err.println("No existen impresoras instaladas");
    }

    inputStream.close();
    //imprimirFin(subTotal, total, dineroR, devolucion); //ESTE METODO NO SE UTILIZARA

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al imprimir "+e);
    }

}
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B_volver;
    private javax.swing.JPopupMenu PoElimina;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total3;
    private javax.swing.JLabel Total4;
    private javax.swing.JLabel Total5;
    private javax.swing.JLabel TotalaPagar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnNuevaVenat;
    private javax.swing.JLabel cambio;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelStok;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JButton txtImprime;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables
}
